wildfy:
  build: wildfly
  ports:
    - 8080:8080
    - 9990:9990
    - 43678:43678
    - 9092:9092
  links:
    - postgresdb
  volumes:
    - ./deployments:/opt/jboss/wildfly/standalone/deployments/
postgresdb:
  build: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: nitro
  ports:
    - 5432:5432
